apiVersion: v1
kind: Namespace
metadata:
  name: development
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-001
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pcv-001
spec:
  storageClassName: sc-001
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  namespace: development
  name:  mongo-svc
  labels:
    app: mongo-label
spec:
  clusterIP: None
  ports:
  - port:  27017
    name:  mongo-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: development
  name: mongo
spec:
  serviceName: "mongo-service"
  replicas: 2
  selector:
    matchLabels:
      app: mongo-label
  template:
    metadata:
      labels:
        app: mongo-label
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo
          name:  mongo-container
          ports:  
            - containerPort: 27017
          volumeMounts:
            - name: pv-storage
              mountPath: /data/db
          resources:
            requests:
              cpu: 1
              memory: 2Gi
      volumes:
        - name:  pv-storage
          persistentVolumeClaim:
            claimName: pvc-001